### PR TITLE
Add a linter to check the images' alt text

### PR DESCRIPTION
**Pull request by arnaucasau**
In order to meet the [IBM Accessibility Requirements](https://www.ibm.com/able/requirements/requirements) for the API docs, we need to ensure that all images have appropriate alt text so that users can understand any meaningful visuals. The alt text should serve the same purpose as the images on the page, conveying the same meaning rather than describing visual characteristics. In addition, if an image contains important words for understanding the content, the alt text should include those words as well.

This PR adds a linter to check that all images have alt text. The current invalid images, if any, have been included in an allowlist that will help us to not break CI before the text is added.

If the script detects an image without alt text, it will show an error indicating the file where the image is located and the line where we are using a sphinx directive like `.. image::` or `.. plot::` that generates an image. Example:

```
💔 Some images are missing the alt text

Errors found in qiskit_ibm_runtime/fake_provider/__init__.py:
- Error in line 34: .. plot::

Alt text is crucial for making documentation accessible to all users. It should serve the same purpose as the images on the page, conveying the same meaning rather than describing visual characteristics. When an image contains words that are important to understanding the content, the alt text should include those words as well.
```

To fix the error, the `:alt: [Your text here]` option must be added under the lines indicated in the error messages. However, If the `.. plot::` directive is used, but no image is generated, you can use the option `:nofigs:`.

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]

**Comment by garrison** [comment]
Thank you for the contribution.

This PR creates a `tools/` directory, and if we merge it we also ought to add `tools/` to the various lint commands in `tox.ini` before doing so.

How often do we expect changes to this file?  Have you considered the alternative of hosting it in a central repository, rather than having it be duplicated across many repositories?  This is what we eventually ended up doing with [extremal-python-dependencies](https://github.com/IBM/extremal-python-dependencies).

Or, is there an existing general-purpose tool we could use instead?

**Comment by arnaucasau** [comment]
Thank you for the review!! As we discussed over Slack, I changed the PR to install the linter from a central repository. Instead of creating a new repo and publish to PyPI we decided to follow the same strategy as our notebook tester and host the code in `qiskit/documentation`.

In the commit https://github.com/Qiskit/qiskit-addon-utils/pull/63/commits/77f6e8cb725d1efaf1d6c8cb0b3b8a76e539be50, I removed the `tools/` directory and used the VCS method to install the package specifying a commit hash to avoid breaking CI in case we modify the linter in the future. Lastly, in the commit https://github.com/Qiskit/qiskit-addon-utils/pull/63/commits/e5807c7688562116d8b45dd08c238af926acee85, I added a file to skip given that we have an image without alt text as you can see in https://github.com/Qiskit/qiskit-addon-utils/actions/runs/12234490132/job/34123796641. This is temporary until we fix the image and ideally we shouldn't have any file to skip ever.

Once the PR gets approved and merged, I'll change my other PRs to the rest of the addons to remove the `tools/` directory matching this one :)

**Comment by garrison** [comment]
First reaction: Thank you, this is awesome!

I will look carefully at everything in a bit.

**Review by garrison — APPROVED** [review]
This is wonderful, thank you!

**Pull request merged**
