### PR TITLE
Speed up tox and ci

### PR DESCRIPTION
**Pull request by garrison**
- ~~Use [tox-uv] (may not work on every addon, but seems to work for this one)~~
- Execute environments in parallel
- Install from a wheel in tox (quicker than an sdist)

Note: I did not add tox-uv to the minimum version tests, because it would require us to bump the minimum tox version to at least 4.12.1, which was released on Jan 16, 2024 (the current minimum version we support was released on Jan 30, 2023).

Some credit to a post I read recently: https://hynek.me/articles/turbo-charge-tox/

[tox-uv]: https://github.com/tox-dev/tox-uv

### CODE REVIEW

**Comment by garrison** [comment]
This leaves the development version tests as still taking the longest by far.  But we could fix this in the future if we could have the Qiskit SDK CI pipelines build a wheel of the `main` branch upon each change in a way that is available to this pipeline; then we wouldn't have to rebuild it ourselves each time.

**Comment by garrison** [comment]
Interesting intermittent CI failure at https://github.com/Qiskit/qiskit-addon-utils/actions/runs/10804106388/job/29969030179?pr=18 (see immediately under "Test using tox environment").  This might not be a total dealbreaker, though: I'd almost rather have to restart jobs now and then if it means having the CI finish much sooner.  But it is a tradeoff.  I wonder how often we will see an intermittent bug like this.

**Comment by mrossinek** [comment]
I have been thinking, also as part of #17, that the reason for the slow speed of the development tests is that the `Qiskit` wheel has to be built 3 times. Can we instead clone Qiskit once, build its wheel once, and then have each tox env install it from there?
I would rather do smth like than introduce potentially flaky CI. Waiting 20sec instead of 1min can be considered nice, but 1min is still _very_ fast in my opinion.

**Comment by mrossinek** [comment]
How about #20? It does not have to fully replace this PR but it resolves must of the slowdown (the apparent slow down right now is still due to the fact that doctest runs on Python 3.10 rather than the correct Python version which triggers a second wheel build rather than use the cache; will be fixed by #19).

**Comment by mrossinek** [comment]
Development tests now only take ~5 mins. Is that sufficiently fast or would you like this PR to go on top as well?
https://github.com/Qiskit/qiskit-addon-utils/actions/runs/10812540301/job/29994411496

Updating things here should let us know how much faster it might get..

**Comment by garrison** [comment]
I've seen two weird CI failures now on the dev tests.  I can only imagine there must be some race condition when multiple attempts to build the same qiskit wheel are made in parallel.

**Review by mrossinek — APPROVED** [review]
Thanks, this looks great :+1:

After this, the bottleneck will remain to be the dev tests (which they will always remain), but the speed improvement on the latest and minimum version tests is nice :+1:

**Pull request merged**
